FROM python:3.12-slim AS builder

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv
WORKDIR /app
ENV UV_COMPILE_BYTECODE=1
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --no-cache


FROM python:3.12-slim
WORKDIR /app
RUN mkdir /app/data
COPY --from=builder /app/.venv /app/.venv
COPY lab1 ./lab1
RUN useradd -m appuser && chown -R appuser /app
USER appuser
ENV PATH="/app/.venv/bin:$PATH"
CMD ["uvicorn", "lab1.main:app", "--host", "0.0.0.0", "--port", "8000"]
